import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['var(--font-display)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        mono:    ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
      },
      colors: {
        // ── HydroSource dark command center token system ──────────────────
        'primary-container':          '#00f2ff',
        'primary-fixed':              '#74f5ff',
        'primary-fixed-dim':          '#00dbe7',
        'on-primary':                 '#00363a',
        'on-primary-container':       '#006a71',
        'on-primary-fixed':           '#002022',
        'on-primary-fixed-variant':   '#004f54',
        'inverse-primary':            '#00696f',
        'surface-tint':               '#00dbe7',
        'background':                 '#0f1419',
        'on-background':              '#dee3ea',
        'surface':                    '#0f1419',
        'surface-dim':                '#0f1419',
        'surface-bright':             '#353a3f',
        'surface-container-lowest':   '#0a0f14',
        'surface-container-low':      '#171c21',
        'surface-container':          '#1b2025',
        'surface-container-high':     '#252a30',
        'surface-container-highest':  '#30353b',
        'on-surface':                 '#dee3ea',
        'on-surface-variant':         '#b9cacb',
        'surface-variant':            '#30353b',
        'inverse-surface':            '#dee3ea',
        'inverse-on-surface':         '#2c3137',
        'outline':                    '#849495',
        'outline-variant':            '#3a494b',
        'secondary':                  '#b1c5ff',
        'secondary-container':        '#0148ab',
        'secondary-fixed':            '#dae2ff',
        'secondary-fixed-dim':        '#b1c5ff',
        'on-secondary':               '#002c70',
        'on-secondary-container':     '#a6beff',
        'on-secondary-fixed':         '#001946',
        'on-secondary-fixed-variant': '#00419e',
        'tertiary':                   '#dcfff7',
        'tertiary-container':         '#59f2dc',
        'tertiary-fixed':             '#62fae3',
        'tertiary-fixed-dim':         '#3cddc7',
        'on-tertiary':                '#003731',
        'on-tertiary-container':      '#006c60',
        'on-tertiary-fixed':          '#00201c',
        'on-tertiary-fixed-variant':  '#005047',
        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'on-error':                   '#690005',
        'on-error-container':         '#ffdad6',
        'primary': '#e1fdff',
        // ── Legacy tokens (kept for backwards compatibility) ──────────────
        pool: {
          50:  '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc8fb',
          400: '#36aaf6',
          500: '#0c8de8',
          600: '#006FFF',
          700: '#0057cc',
          800: '#0049a8',
          900: '#063e8a',
        },
        teal: {
          50:  '#F0FDF9',
          100: '#CCFBF1',
          400: '#2DD4BF',
          500: '#00C9B1',
          600: '#00A99A',
          700: '#00877B',
        },
        safe:     '#3cddc7',
        caution:  '#b1c5ff',
        critical: '#ffb4ab',
        ink:     '#0a0f14',
        page:    '#0f1419',
        slate: {
          50:  '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
      },
      backgroundImage: {
        'pool-gradient': 'linear-gradient(135deg, #006FFF 0%, #00D4AA 100%)',
        'hero-gradient': 'linear-gradient(135deg, #0B1120 0%, #0a1f44 50%, #003380 100%)',
        'safe-gradient': 'linear-gradient(135deg, #00C17A, #00a86b)',
        'caution-gradient': 'linear-gradient(135deg, #FFB830, #f59e0b)',
        'critical-gradient': 'linear-gradient(135deg, #FF3B5C, #e11d48)',
        'card-shimmer': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.4) 50%, transparent 100%)',
      },
      boxShadow: {
        'glow-blue': '0 0 20px rgba(0, 111, 255, 0.4)',
        'glow-safe': '0 0 20px rgba(0, 193, 122, 0.4)',
        'glow-caution': '0 0 20px rgba(255, 184, 48, 0.4)',
        'glow-critical': '0 0 20px rgba(255, 59, 92, 0.5)',
        'card': '0 1px 3px rgba(0,0,0,0.04), 0 4px 16px rgba(0,0,0,0.06)',
        'card-hover': '0 8px 32px rgba(0,0,0,0.12)',
        'float': '0 20px 60px rgba(0, 111, 255, 0.2)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'slide-up': 'slide-up 0.5s ease forwards',
        'shimmer': 'shimmer 2s infinite',
        'pop': 'pop 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'ripple': 'ripple 1.5s ease-out infinite',
        'gradient': 'gradient-flow 4s ease infinite',
        'wave': 'wave 3s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.05)' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        pop: {
          '0%': { transform: 'scale(0.7)', opacity: '0' },
          '70%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        ripple: {
          '0%': { transform: 'scale(1)', opacity: '0.6' },
          '100%': { transform: 'scale(3)', opacity: '0' },
        },
        'gradient-flow': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        wave: {
          '0%, 100%': { transform: 'scaleY(1)' },
          '50%': { transform: 'scaleY(0.85)' },
        },
      },
      spacing: {
        'gutter':    '16px',
        'margin':    '24px',
        'bento_gap': '12px',
        'base':      '4px',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
}

export default config
